/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ABooleanoPalavraTipoBase extends PTipoBase
{
    private TBooleanoPalavra _booleanoPalavra_;

    public ABooleanoPalavraTipoBase()
    {
        // Constructor
    }

    public ABooleanoPalavraTipoBase(
        @SuppressWarnings("hiding") TBooleanoPalavra _booleanoPalavra_)
    {
        // Constructor
        setBooleanoPalavra(_booleanoPalavra_);

    }

    @Override
    public Object clone()
    {
        return new ABooleanoPalavraTipoBase(
            cloneNode(this._booleanoPalavra_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseABooleanoPalavraTipoBase(this);
    }

    public TBooleanoPalavra getBooleanoPalavra()
    {
        return this._booleanoPalavra_;
    }

    public void setBooleanoPalavra(TBooleanoPalavra node)
    {
        if(this._booleanoPalavra_ != null)
        {
            this._booleanoPalavra_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._booleanoPalavra_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._booleanoPalavra_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._booleanoPalavra_ == child)
        {
            this._booleanoPalavra_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._booleanoPalavra_ == oldChild)
        {
            setBooleanoPalavra((TBooleanoPalavra) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
