/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AComandoSemOpcionalComando extends PComando
{
    private PComandoSemCasam _comandoSemCasam_;

    public AComandoSemOpcionalComando()
    {
        // Constructor
    }

    public AComandoSemOpcionalComando(
        @SuppressWarnings("hiding") PComandoSemCasam _comandoSemCasam_)
    {
        // Constructor
        setComandoSemCasam(_comandoSemCasam_);

    }

    @Override
    public Object clone()
    {
        return new AComandoSemOpcionalComando(
            cloneNode(this._comandoSemCasam_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComandoSemOpcionalComando(this);
    }

    public PComandoSemCasam getComandoSemCasam()
    {
        return this._comandoSemCasam_;
    }

    public void setComandoSemCasam(PComandoSemCasam node)
    {
        if(this._comandoSemCasam_ != null)
        {
            this._comandoSemCasam_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoSemCasam_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoSemCasam_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoSemCasam_ == child)
        {
            this._comandoSemCasam_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comandoSemCasam_ == oldChild)
        {
            setComandoSemCasam((PComandoSemCasam) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
