/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ANivelUmNivelUm extends PNivelUm
{
    private PNivelUm _nivelUm_;
    private PPreceE _preceE_;
    private PNivelDois _nivelDois_;

    public ANivelUmNivelUm()
    {
        // Constructor
    }

    public ANivelUmNivelUm(
        @SuppressWarnings("hiding") PNivelUm _nivelUm_,
        @SuppressWarnings("hiding") PPreceE _preceE_,
        @SuppressWarnings("hiding") PNivelDois _nivelDois_)
    {
        // Constructor
        setNivelUm(_nivelUm_);

        setPreceE(_preceE_);

        setNivelDois(_nivelDois_);

    }

    @Override
    public Object clone()
    {
        return new ANivelUmNivelUm(
            cloneNode(this._nivelUm_),
            cloneNode(this._preceE_),
            cloneNode(this._nivelDois_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANivelUmNivelUm(this);
    }

    public PNivelUm getNivelUm()
    {
        return this._nivelUm_;
    }

    public void setNivelUm(PNivelUm node)
    {
        if(this._nivelUm_ != null)
        {
            this._nivelUm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nivelUm_ = node;
    }

    public PPreceE getPreceE()
    {
        return this._preceE_;
    }

    public void setPreceE(PPreceE node)
    {
        if(this._preceE_ != null)
        {
            this._preceE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._preceE_ = node;
    }

    public PNivelDois getNivelDois()
    {
        return this._nivelDois_;
    }

    public void setNivelDois(PNivelDois node)
    {
        if(this._nivelDois_ != null)
        {
            this._nivelDois_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nivelDois_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nivelUm_)
            + toString(this._preceE_)
            + toString(this._nivelDois_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nivelUm_ == child)
        {
            this._nivelUm_ = null;
            return;
        }

        if(this._preceE_ == child)
        {
            this._preceE_ = null;
            return;
        }

        if(this._nivelDois_ == child)
        {
            this._nivelDois_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nivelUm_ == oldChild)
        {
            setNivelUm((PNivelUm) newChild);
            return;
        }

        if(this._preceE_ == oldChild)
        {
            setPreceE((PPreceE) newChild);
            return;
        }

        if(this._nivelDois_ == oldChild)
        {
            setNivelDois((PNivelDois) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
