/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ANivelTresNivelTres extends PNivelTres
{
    private PNivelTres _nivelTres_;
    private PPreceMaiorMenorIgual _preceMaiorMenorIgual_;
    private PNivelQuatro _nivelQuatro_;

    public ANivelTresNivelTres()
    {
        // Constructor
    }

    public ANivelTresNivelTres(
        @SuppressWarnings("hiding") PNivelTres _nivelTres_,
        @SuppressWarnings("hiding") PPreceMaiorMenorIgual _preceMaiorMenorIgual_,
        @SuppressWarnings("hiding") PNivelQuatro _nivelQuatro_)
    {
        // Constructor
        setNivelTres(_nivelTres_);

        setPreceMaiorMenorIgual(_preceMaiorMenorIgual_);

        setNivelQuatro(_nivelQuatro_);

    }

    @Override
    public Object clone()
    {
        return new ANivelTresNivelTres(
            cloneNode(this._nivelTres_),
            cloneNode(this._preceMaiorMenorIgual_),
            cloneNode(this._nivelQuatro_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANivelTresNivelTres(this);
    }

    public PNivelTres getNivelTres()
    {
        return this._nivelTres_;
    }

    public void setNivelTres(PNivelTres node)
    {
        if(this._nivelTres_ != null)
        {
            this._nivelTres_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nivelTres_ = node;
    }

    public PPreceMaiorMenorIgual getPreceMaiorMenorIgual()
    {
        return this._preceMaiorMenorIgual_;
    }

    public void setPreceMaiorMenorIgual(PPreceMaiorMenorIgual node)
    {
        if(this._preceMaiorMenorIgual_ != null)
        {
            this._preceMaiorMenorIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._preceMaiorMenorIgual_ = node;
    }

    public PNivelQuatro getNivelQuatro()
    {
        return this._nivelQuatro_;
    }

    public void setNivelQuatro(PNivelQuatro node)
    {
        if(this._nivelQuatro_ != null)
        {
            this._nivelQuatro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nivelQuatro_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nivelTres_)
            + toString(this._preceMaiorMenorIgual_)
            + toString(this._nivelQuatro_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nivelTres_ == child)
        {
            this._nivelTres_ = null;
            return;
        }

        if(this._preceMaiorMenorIgual_ == child)
        {
            this._preceMaiorMenorIgual_ = null;
            return;
        }

        if(this._nivelQuatro_ == child)
        {
            this._nivelQuatro_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nivelTres_ == oldChild)
        {
            setNivelTres((PNivelTres) newChild);
            return;
        }

        if(this._preceMaiorMenorIgual_ == oldChild)
        {
            setPreceMaiorMenorIgual((PPreceMaiorMenorIgual) newChild);
            return;
        }

        if(this._nivelQuatro_ == oldChild)
        {
            setNivelQuatro((PNivelQuatro) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
