/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ANivelDoisNivelDois extends PNivelDois
{
    private PNivelDois _nivelDois_;
    private PPreceIgual _preceIgual_;
    private PNivelTres _nivelTres_;

    public ANivelDoisNivelDois()
    {
        // Constructor
    }

    public ANivelDoisNivelDois(
        @SuppressWarnings("hiding") PNivelDois _nivelDois_,
        @SuppressWarnings("hiding") PPreceIgual _preceIgual_,
        @SuppressWarnings("hiding") PNivelTres _nivelTres_)
    {
        // Constructor
        setNivelDois(_nivelDois_);

        setPreceIgual(_preceIgual_);

        setNivelTres(_nivelTres_);

    }

    @Override
    public Object clone()
    {
        return new ANivelDoisNivelDois(
            cloneNode(this._nivelDois_),
            cloneNode(this._preceIgual_),
            cloneNode(this._nivelTres_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANivelDoisNivelDois(this);
    }

    public PNivelDois getNivelDois()
    {
        return this._nivelDois_;
    }

    public void setNivelDois(PNivelDois node)
    {
        if(this._nivelDois_ != null)
        {
            this._nivelDois_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nivelDois_ = node;
    }

    public PPreceIgual getPreceIgual()
    {
        return this._preceIgual_;
    }

    public void setPreceIgual(PPreceIgual node)
    {
        if(this._preceIgual_ != null)
        {
            this._preceIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._preceIgual_ = node;
    }

    public PNivelTres getNivelTres()
    {
        return this._nivelTres_;
    }

    public void setNivelTres(PNivelTres node)
    {
        if(this._nivelTres_ != null)
        {
            this._nivelTres_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nivelTres_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nivelDois_)
            + toString(this._preceIgual_)
            + toString(this._nivelTres_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nivelDois_ == child)
        {
            this._nivelDois_ = null;
            return;
        }

        if(this._preceIgual_ == child)
        {
            this._preceIgual_ = null;
            return;
        }

        if(this._nivelTres_ == child)
        {
            this._nivelTres_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nivelDois_ == oldChild)
        {
            setNivelDois((PNivelDois) newChild);
            return;
        }

        if(this._preceIgual_ == oldChild)
        {
            setPreceIgual((PPreceIgual) newChild);
            return;
        }

        if(this._nivelTres_ == oldChild)
        {
            setNivelTres((PNivelTres) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
