/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ANivelTresNivelDois extends PNivelDois
{
    private PNivelTres _nivelTres_;

    public ANivelTresNivelDois()
    {
        // Constructor
    }

    public ANivelTresNivelDois(
        @SuppressWarnings("hiding") PNivelTres _nivelTres_)
    {
        // Constructor
        setNivelTres(_nivelTres_);

    }

    @Override
    public Object clone()
    {
        return new ANivelTresNivelDois(
            cloneNode(this._nivelTres_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANivelTresNivelDois(this);
    }

    public PNivelTres getNivelTres()
    {
        return this._nivelTres_;
    }

    public void setNivelTres(PNivelTres node)
    {
        if(this._nivelTres_ != null)
        {
            this._nivelTres_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nivelTres_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nivelTres_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nivelTres_ == child)
        {
            this._nivelTres_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nivelTres_ == oldChild)
        {
            setNivelTres((PNivelTres) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
