/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ANivelDoisNivelUm extends PNivelUm
{
    private PNivelDois _nivelDois_;

    public ANivelDoisNivelUm()
    {
        // Constructor
    }

    public ANivelDoisNivelUm(
        @SuppressWarnings("hiding") PNivelDois _nivelDois_)
    {
        // Constructor
        setNivelDois(_nivelDois_);

    }

    @Override
    public Object clone()
    {
        return new ANivelDoisNivelUm(
            cloneNode(this._nivelDois_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANivelDoisNivelUm(this);
    }

    public PNivelDois getNivelDois()
    {
        return this._nivelDois_;
    }

    public void setNivelDois(PNivelDois node)
    {
        if(this._nivelDois_ != null)
        {
            this._nivelDois_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nivelDois_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nivelDois_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nivelDois_ == child)
        {
            this._nivelDois_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nivelDois_ == oldChild)
        {
            setNivelDois((PNivelDois) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
