/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ANivelQuatroNivelQuatro extends PNivelQuatro
{
    private PNivelQuatro _nivelQuatro_;
    private PPreceSomaMenos _preceSomaMenos_;
    private PNivelCinco _nivelCinco_;

    public ANivelQuatroNivelQuatro()
    {
        // Constructor
    }

    public ANivelQuatroNivelQuatro(
        @SuppressWarnings("hiding") PNivelQuatro _nivelQuatro_,
        @SuppressWarnings("hiding") PPreceSomaMenos _preceSomaMenos_,
        @SuppressWarnings("hiding") PNivelCinco _nivelCinco_)
    {
        // Constructor
        setNivelQuatro(_nivelQuatro_);

        setPreceSomaMenos(_preceSomaMenos_);

        setNivelCinco(_nivelCinco_);

    }

    @Override
    public Object clone()
    {
        return new ANivelQuatroNivelQuatro(
            cloneNode(this._nivelQuatro_),
            cloneNode(this._preceSomaMenos_),
            cloneNode(this._nivelCinco_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANivelQuatroNivelQuatro(this);
    }

    public PNivelQuatro getNivelQuatro()
    {
        return this._nivelQuatro_;
    }

    public void setNivelQuatro(PNivelQuatro node)
    {
        if(this._nivelQuatro_ != null)
        {
            this._nivelQuatro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nivelQuatro_ = node;
    }

    public PPreceSomaMenos getPreceSomaMenos()
    {
        return this._preceSomaMenos_;
    }

    public void setPreceSomaMenos(PPreceSomaMenos node)
    {
        if(this._preceSomaMenos_ != null)
        {
            this._preceSomaMenos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._preceSomaMenos_ = node;
    }

    public PNivelCinco getNivelCinco()
    {
        return this._nivelCinco_;
    }

    public void setNivelCinco(PNivelCinco node)
    {
        if(this._nivelCinco_ != null)
        {
            this._nivelCinco_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nivelCinco_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nivelQuatro_)
            + toString(this._preceSomaMenos_)
            + toString(this._nivelCinco_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nivelQuatro_ == child)
        {
            this._nivelQuatro_ = null;
            return;
        }

        if(this._preceSomaMenos_ == child)
        {
            this._preceSomaMenos_ = null;
            return;
        }

        if(this._nivelCinco_ == child)
        {
            this._nivelCinco_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nivelQuatro_ == oldChild)
        {
            setNivelQuatro((PNivelQuatro) newChild);
            return;
        }

        if(this._preceSomaMenos_ == oldChild)
        {
            setPreceSomaMenos((PPreceSomaMenos) newChild);
            return;
        }

        if(this._nivelCinco_ == oldChild)
        {
            setNivelCinco((PNivelCinco) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
