/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ANivelCincoNivelQuatro extends PNivelQuatro
{
    private PNivelCinco _nivelCinco_;

    public ANivelCincoNivelQuatro()
    {
        // Constructor
    }

    public ANivelCincoNivelQuatro(
        @SuppressWarnings("hiding") PNivelCinco _nivelCinco_)
    {
        // Constructor
        setNivelCinco(_nivelCinco_);

    }

    @Override
    public Object clone()
    {
        return new ANivelCincoNivelQuatro(
            cloneNode(this._nivelCinco_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANivelCincoNivelQuatro(this);
    }

    public PNivelCinco getNivelCinco()
    {
        return this._nivelCinco_;
    }

    public void setNivelCinco(PNivelCinco node)
    {
        if(this._nivelCinco_ != null)
        {
            this._nivelCinco_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nivelCinco_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nivelCinco_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nivelCinco_ == child)
        {
            this._nivelCinco_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nivelCinco_ == oldChild)
        {
            setNivelCinco((PNivelCinco) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
