/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ANivelSeisNivelSeis extends PNivelSeis
{
    private PPreceNao _preceNao_;
    private PNivelSeis _nivelSeis_;

    public ANivelSeisNivelSeis()
    {
        // Constructor
    }

    public ANivelSeisNivelSeis(
        @SuppressWarnings("hiding") PPreceNao _preceNao_,
        @SuppressWarnings("hiding") PNivelSeis _nivelSeis_)
    {
        // Constructor
        setPreceNao(_preceNao_);

        setNivelSeis(_nivelSeis_);

    }

    @Override
    public Object clone()
    {
        return new ANivelSeisNivelSeis(
            cloneNode(this._preceNao_),
            cloneNode(this._nivelSeis_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANivelSeisNivelSeis(this);
    }

    public PPreceNao getPreceNao()
    {
        return this._preceNao_;
    }

    public void setPreceNao(PPreceNao node)
    {
        if(this._preceNao_ != null)
        {
            this._preceNao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._preceNao_ = node;
    }

    public PNivelSeis getNivelSeis()
    {
        return this._nivelSeis_;
    }

    public void setNivelSeis(PNivelSeis node)
    {
        if(this._nivelSeis_ != null)
        {
            this._nivelSeis_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nivelSeis_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._preceNao_)
            + toString(this._nivelSeis_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._preceNao_ == child)
        {
            this._preceNao_ = null;
            return;
        }

        if(this._nivelSeis_ == child)
        {
            this._nivelSeis_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._preceNao_ == oldChild)
        {
            setPreceNao((PPreceNao) newChild);
            return;
        }

        if(this._nivelSeis_ == oldChild)
        {
            setNivelSeis((PNivelSeis) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
