/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ANivelCincoNivelCinco extends PNivelCinco
{
    private PNivelCinco _nivelCinco_;
    private PPreceMultDiv _preceMultDiv_;
    private PNivelSeis _nivelSeis_;

    public ANivelCincoNivelCinco()
    {
        // Constructor
    }

    public ANivelCincoNivelCinco(
        @SuppressWarnings("hiding") PNivelCinco _nivelCinco_,
        @SuppressWarnings("hiding") PPreceMultDiv _preceMultDiv_,
        @SuppressWarnings("hiding") PNivelSeis _nivelSeis_)
    {
        // Constructor
        setNivelCinco(_nivelCinco_);

        setPreceMultDiv(_preceMultDiv_);

        setNivelSeis(_nivelSeis_);

    }

    @Override
    public Object clone()
    {
        return new ANivelCincoNivelCinco(
            cloneNode(this._nivelCinco_),
            cloneNode(this._preceMultDiv_),
            cloneNode(this._nivelSeis_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANivelCincoNivelCinco(this);
    }

    public PNivelCinco getNivelCinco()
    {
        return this._nivelCinco_;
    }

    public void setNivelCinco(PNivelCinco node)
    {
        if(this._nivelCinco_ != null)
        {
            this._nivelCinco_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nivelCinco_ = node;
    }

    public PPreceMultDiv getPreceMultDiv()
    {
        return this._preceMultDiv_;
    }

    public void setPreceMultDiv(PPreceMultDiv node)
    {
        if(this._preceMultDiv_ != null)
        {
            this._preceMultDiv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._preceMultDiv_ = node;
    }

    public PNivelSeis getNivelSeis()
    {
        return this._nivelSeis_;
    }

    public void setNivelSeis(PNivelSeis node)
    {
        if(this._nivelSeis_ != null)
        {
            this._nivelSeis_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nivelSeis_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nivelCinco_)
            + toString(this._preceMultDiv_)
            + toString(this._nivelSeis_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nivelCinco_ == child)
        {
            this._nivelCinco_ = null;
            return;
        }

        if(this._preceMultDiv_ == child)
        {
            this._preceMultDiv_ = null;
            return;
        }

        if(this._nivelSeis_ == child)
        {
            this._nivelSeis_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nivelCinco_ == oldChild)
        {
            setNivelCinco((PNivelCinco) newChild);
            return;
        }

        if(this._preceMultDiv_ == oldChild)
        {
            setPreceMultDiv((PPreceMultDiv) newChild);
            return;
        }

        if(this._nivelSeis_ == oldChild)
        {
            setNivelSeis((PNivelSeis) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
