/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ANivelZeroExp extends PExp
{
    private PExp _exp_;
    private PPreceOu _preceOu_;
    private PNivelUm _nivelUm_;

    public ANivelZeroExp()
    {
        // Constructor
    }

    public ANivelZeroExp(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") PPreceOu _preceOu_,
        @SuppressWarnings("hiding") PNivelUm _nivelUm_)
    {
        // Constructor
        setExp(_exp_);

        setPreceOu(_preceOu_);

        setNivelUm(_nivelUm_);

    }

    @Override
    public Object clone()
    {
        return new ANivelZeroExp(
            cloneNode(this._exp_),
            cloneNode(this._preceOu_),
            cloneNode(this._nivelUm_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANivelZeroExp(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PPreceOu getPreceOu()
    {
        return this._preceOu_;
    }

    public void setPreceOu(PPreceOu node)
    {
        if(this._preceOu_ != null)
        {
            this._preceOu_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._preceOu_ = node;
    }

    public PNivelUm getNivelUm()
    {
        return this._nivelUm_;
    }

    public void setNivelUm(PNivelUm node)
    {
        if(this._nivelUm_ != null)
        {
            this._nivelUm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nivelUm_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._preceOu_)
            + toString(this._nivelUm_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._preceOu_ == child)
        {
            this._preceOu_ = null;
            return;
        }

        if(this._nivelUm_ == child)
        {
            this._nivelUm_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._preceOu_ == oldChild)
        {
            setPreceOu((PPreceOu) newChild);
            return;
        }

        if(this._nivelUm_ == oldChild)
        {
            setNivelUm((PNivelUm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
