/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class TPalavraVazio extends Token
{
    public TPalavraVazio()
    {
        super.setText("vazio");
    }

    public TPalavraVazio(int line, int pos)
    {
        super.setText("vazio");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPalavraVazio(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPalavraVazio(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPalavraVazio text.");
    }
}
