/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.analysis;

import java.util.*;
import caju.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAProgramaAPrograma(AAProgramaAPrograma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADecVariavelADecVariavel(ADecVariavelADecVariavel node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIdentificadoresAListaNomes(AIdentificadoresAListaNomes node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIdentificadorAListaNomes(AIdentificadorAListaNomes node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATipoBaseATipo(ATipoBaseATipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVetorATipo(AVetorATipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExpressaoAVetorEstrela(AExpressaoAVetorEstrela node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABooleanoPalavraATipoBase(ABooleanoPalavraATipoBase node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACaracterePalavraATipoBase(ACaracterePalavraATipoBase node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANumeroPalavraATipoBase(ANumeroPalavraATipoBase node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADecFuncaoADecFuncao(ADecFuncaoADecFuncao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATipoATipoRetorno(ATipoATipoRetorno node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVazioATipoRetorno(AVazioATipoRetorno node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParametrosAParametros(AParametrosAParametros node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANadaAParametros(ANadaAParametros node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParametroAParametro(AParametroAParametro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParametroEstrelaAParametroEstrela(AParametroEstrelaAParametroEstrela node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlocoABloco(ABlocoABloco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAtribAAtrib(AAtribAAtrib node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAListaAtribAListaAtrib(AListaAtribAListaAtrib node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAtribEstrelaAAtribEstrela(AAtribEstrelaAAtribEstrela node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASeAComandoCasado(ASeAComandoCasado node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOutraAComandoCasado(AOutraAComandoCasado node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASeAComandoNaoCasado(ASeAComandoNaoCasado node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASeSenaoAComandoNaoCasado(ASeSenaoAComandoNaoCasado node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComandoCasadoAComando(AComandoCasadoAComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComandoNaoCasadoAComando(AComandoNaoCasadoAComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEnquantoAOutra(AEnquantoAOutra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParaAOutra(AParaAOutra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParaCadaAOutra(AParaCadaAOutra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAtribPontoAOutra(AAtribPontoAOutra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARetorneAOutra(ARetorneAOutra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlocoAOutra(ABlocoAOutra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAChamadaAOutra(AChamadaAOutra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIdentificadorAVar(AIdentificadorAVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVarAVar(AVarAVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASomaAExp(ASomaAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMenosAExp(AMenosAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultAExp(AMultAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADivAExp(ADivAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIgualAExp(AIgualAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMenorAExp(AMenorAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMaiorAExp(AMaiorAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMenorIgualAExp(AMenorIgualAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMaiorIgualAExp(AMaiorIgualAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEAExp(AEAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOuAExp(AOuAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANaoAExp(ANaoAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAChamadaAExp(AChamadaAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParAExp(AParAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVarAExp(AVarAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANumeroAExp(ANumeroAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACaractereAExp(ACaractereAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABooleanoAExp(ABooleanoAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAStringAExp(AStringAExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAChamadaAChamada(AChamadaAChamada node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANadaAListaExp(ANadaAListaExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExpAListaExp(AExpAListaExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOuExpEstrelaAOuExpEstrela(AOuExpEstrelaAOuExpEstrela node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNumero(TNumero node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSoma(TSoma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMenos(TMenos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMult(TMult node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDiv(TDiv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIgual(TIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMaior(TMaior node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMenor(TMenor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMaiorIgual(TMaiorIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMenorIgual(TMenorIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTInicio(TInicio node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFim(TFim node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBooleanoPalavra(TBooleanoPalavra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNumeroPalavra(TNumeroPalavra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCaracterePalavra(TCaracterePalavra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVetorPalavra(TVetorPalavra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPalavraVazio(TPalavraVazio node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTString(TString node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParEsq(TParEsq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParDir(TParDir node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTColcheteEsq(TColcheteEsq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTColcheteDir(TColcheteDir node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPonto(TPonto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVirgula(TVirgula node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBarra(TBarra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPontoEVirgula(TPontoEVirgula node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIniciador(TIniciador node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAtribuicao(TAtribuicao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDoisPontos(TDoisPontos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBooleano(TBooleano node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEnquanto(TEnquanto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParaCada(TParaCada node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPara(TPara node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRetorne(TRetorne node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSe(TSe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSenao(TSenao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNao(TNao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTE(TE node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOu(TOu node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVazio(TVazio node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCaractere(TCaractere node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIdentificador(TIdentificador node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComentarioLinha(TComentarioLinha node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComentarioBloco(TComentarioBloco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
