/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.analysis;

import java.util.*;
import caju.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPAPrograma().apply(this);
        outStart(node);
    }

    public void inAAProgramaAPrograma(AAProgramaAPrograma node)
    {
        defaultIn(node);
    }

    public void outAAProgramaAPrograma(AAProgramaAPrograma node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAProgramaAPrograma(AAProgramaAPrograma node)
    {
        inAAProgramaAPrograma(node);
        {
            List<PADecFuncao> copy = new ArrayList<PADecFuncao>(node.getADecFuncao());
            Collections.reverse(copy);
            for(PADecFuncao e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PADecVariavel> copy = new ArrayList<PADecVariavel>(node.getADecVariavel());
            Collections.reverse(copy);
            for(PADecVariavel e : copy)
            {
                e.apply(this);
            }
        }
        outAAProgramaAPrograma(node);
    }

    public void inADecVariavelADecVariavel(ADecVariavelADecVariavel node)
    {
        defaultIn(node);
    }

    public void outADecVariavelADecVariavel(ADecVariavelADecVariavel node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecVariavelADecVariavel(ADecVariavelADecVariavel node)
    {
        inADecVariavelADecVariavel(node);
        if(node.getAListaNomes() != null)
        {
            node.getAListaNomes().apply(this);
        }
        if(node.getATipo() != null)
        {
            node.getATipo().apply(this);
        }
        outADecVariavelADecVariavel(node);
    }

    public void inAIdentificadoresAListaNomes(AIdentificadoresAListaNomes node)
    {
        defaultIn(node);
    }

    public void outAIdentificadoresAListaNomes(AIdentificadoresAListaNomes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdentificadoresAListaNomes(AIdentificadoresAListaNomes node)
    {
        inAIdentificadoresAListaNomes(node);
        if(node.getAListaNomes() != null)
        {
            node.getAListaNomes().apply(this);
        }
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        outAIdentificadoresAListaNomes(node);
    }

    public void inAIdentificadorAListaNomes(AIdentificadorAListaNomes node)
    {
        defaultIn(node);
    }

    public void outAIdentificadorAListaNomes(AIdentificadorAListaNomes node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdentificadorAListaNomes(AIdentificadorAListaNomes node)
    {
        inAIdentificadorAListaNomes(node);
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        outAIdentificadorAListaNomes(node);
    }

    public void inATipoBaseATipo(ATipoBaseATipo node)
    {
        defaultIn(node);
    }

    public void outATipoBaseATipo(ATipoBaseATipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATipoBaseATipo(ATipoBaseATipo node)
    {
        inATipoBaseATipo(node);
        if(node.getATipoBase() != null)
        {
            node.getATipoBase().apply(this);
        }
        outATipoBaseATipo(node);
    }

    public void inAVetorATipo(AVetorATipo node)
    {
        defaultIn(node);
    }

    public void outAVetorATipo(AVetorATipo node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVetorATipo(AVetorATipo node)
    {
        inAVetorATipo(node);
        {
            List<PAVetorEstrela> copy = new ArrayList<PAVetorEstrela>(node.getAVetorEstrela());
            Collections.reverse(copy);
            for(PAVetorEstrela e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getAExp() != null)
        {
            node.getAExp().apply(this);
        }
        if(node.getATipoBase() != null)
        {
            node.getATipoBase().apply(this);
        }
        outAVetorATipo(node);
    }

    public void inAExpressaoAVetorEstrela(AExpressaoAVetorEstrela node)
    {
        defaultIn(node);
    }

    public void outAExpressaoAVetorEstrela(AExpressaoAVetorEstrela node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpressaoAVetorEstrela(AExpressaoAVetorEstrela node)
    {
        inAExpressaoAVetorEstrela(node);
        if(node.getAExp() != null)
        {
            node.getAExp().apply(this);
        }
        outAExpressaoAVetorEstrela(node);
    }

    public void inABooleanoPalavraATipoBase(ABooleanoPalavraATipoBase node)
    {
        defaultIn(node);
    }

    public void outABooleanoPalavraATipoBase(ABooleanoPalavraATipoBase node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABooleanoPalavraATipoBase(ABooleanoPalavraATipoBase node)
    {
        inABooleanoPalavraATipoBase(node);
        if(node.getBooleanoPalavra() != null)
        {
            node.getBooleanoPalavra().apply(this);
        }
        outABooleanoPalavraATipoBase(node);
    }

    public void inACaracterePalavraATipoBase(ACaracterePalavraATipoBase node)
    {
        defaultIn(node);
    }

    public void outACaracterePalavraATipoBase(ACaracterePalavraATipoBase node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACaracterePalavraATipoBase(ACaracterePalavraATipoBase node)
    {
        inACaracterePalavraATipoBase(node);
        if(node.getCaracterePalavra() != null)
        {
            node.getCaracterePalavra().apply(this);
        }
        outACaracterePalavraATipoBase(node);
    }

    public void inANumeroPalavraATipoBase(ANumeroPalavraATipoBase node)
    {
        defaultIn(node);
    }

    public void outANumeroPalavraATipoBase(ANumeroPalavraATipoBase node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumeroPalavraATipoBase(ANumeroPalavraATipoBase node)
    {
        inANumeroPalavraATipoBase(node);
        if(node.getNumeroPalavra() != null)
        {
            node.getNumeroPalavra().apply(this);
        }
        outANumeroPalavraATipoBase(node);
    }

    public void inADecFuncaoADecFuncao(ADecFuncaoADecFuncao node)
    {
        defaultIn(node);
    }

    public void outADecFuncaoADecFuncao(ADecFuncaoADecFuncao node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADecFuncaoADecFuncao(ADecFuncaoADecFuncao node)
    {
        inADecFuncaoADecFuncao(node);
        if(node.getABloco() != null)
        {
            node.getABloco().apply(this);
        }
        if(node.getAParametros() != null)
        {
            node.getAParametros().apply(this);
        }
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        if(node.getATipoRetorno() != null)
        {
            node.getATipoRetorno().apply(this);
        }
        outADecFuncaoADecFuncao(node);
    }

    public void inATipoATipoRetorno(ATipoATipoRetorno node)
    {
        defaultIn(node);
    }

    public void outATipoATipoRetorno(ATipoATipoRetorno node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATipoATipoRetorno(ATipoATipoRetorno node)
    {
        inATipoATipoRetorno(node);
        if(node.getATipo() != null)
        {
            node.getATipo().apply(this);
        }
        outATipoATipoRetorno(node);
    }

    public void inAVazioATipoRetorno(AVazioATipoRetorno node)
    {
        defaultIn(node);
    }

    public void outAVazioATipoRetorno(AVazioATipoRetorno node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVazioATipoRetorno(AVazioATipoRetorno node)
    {
        inAVazioATipoRetorno(node);
        if(node.getPalavraVazio() != null)
        {
            node.getPalavraVazio().apply(this);
        }
        outAVazioATipoRetorno(node);
    }

    public void inAParametrosAParametros(AParametrosAParametros node)
    {
        defaultIn(node);
    }

    public void outAParametrosAParametros(AParametrosAParametros node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParametrosAParametros(AParametrosAParametros node)
    {
        inAParametrosAParametros(node);
        {
            List<PAParametroEstrela> copy = new ArrayList<PAParametroEstrela>(node.getAParametroEstrela());
            Collections.reverse(copy);
            for(PAParametroEstrela e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getAParametro() != null)
        {
            node.getAParametro().apply(this);
        }
        outAParametrosAParametros(node);
    }

    public void inANadaAParametros(ANadaAParametros node)
    {
        defaultIn(node);
    }

    public void outANadaAParametros(ANadaAParametros node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANadaAParametros(ANadaAParametros node)
    {
        inANadaAParametros(node);
        outANadaAParametros(node);
    }

    public void inAParametroAParametro(AParametroAParametro node)
    {
        defaultIn(node);
    }

    public void outAParametroAParametro(AParametroAParametro node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParametroAParametro(AParametroAParametro node)
    {
        inAParametroAParametro(node);
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        if(node.getATipo() != null)
        {
            node.getATipo().apply(this);
        }
        outAParametroAParametro(node);
    }

    public void inAParametroEstrelaAParametroEstrela(AParametroEstrelaAParametroEstrela node)
    {
        defaultIn(node);
    }

    public void outAParametroEstrelaAParametroEstrela(AParametroEstrelaAParametroEstrela node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParametroEstrelaAParametroEstrela(AParametroEstrelaAParametroEstrela node)
    {
        inAParametroEstrelaAParametroEstrela(node);
        if(node.getAParametro() != null)
        {
            node.getAParametro().apply(this);
        }
        outAParametroEstrelaAParametroEstrela(node);
    }

    public void inABlocoABloco(ABlocoABloco node)
    {
        defaultIn(node);
    }

    public void outABlocoABloco(ABlocoABloco node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoABloco(ABlocoABloco node)
    {
        inABlocoABloco(node);
        {
            List<PAComando> copy = new ArrayList<PAComando>(node.getAComando());
            Collections.reverse(copy);
            for(PAComando e : copy)
            {
                e.apply(this);
            }
        }
        {
            List<PADecVariavel> copy = new ArrayList<PADecVariavel>(node.getADecVariavel());
            Collections.reverse(copy);
            for(PADecVariavel e : copy)
            {
                e.apply(this);
            }
        }
        outABlocoABloco(node);
    }

    public void inAAtribAAtrib(AAtribAAtrib node)
    {
        defaultIn(node);
    }

    public void outAAtribAAtrib(AAtribAAtrib node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtribAAtrib(AAtribAAtrib node)
    {
        inAAtribAAtrib(node);
        if(node.getAExp() != null)
        {
            node.getAExp().apply(this);
        }
        if(node.getAVar() != null)
        {
            node.getAVar().apply(this);
        }
        outAAtribAAtrib(node);
    }

    public void inAListaAtribAListaAtrib(AListaAtribAListaAtrib node)
    {
        defaultIn(node);
    }

    public void outAListaAtribAListaAtrib(AListaAtribAListaAtrib node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAListaAtribAListaAtrib(AListaAtribAListaAtrib node)
    {
        inAListaAtribAListaAtrib(node);
        {
            List<PAAtribEstrela> copy = new ArrayList<PAAtribEstrela>(node.getAAtribEstrela());
            Collections.reverse(copy);
            for(PAAtribEstrela e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getAAtrib() != null)
        {
            node.getAAtrib().apply(this);
        }
        outAListaAtribAListaAtrib(node);
    }

    public void inAAtribEstrelaAAtribEstrela(AAtribEstrelaAAtribEstrela node)
    {
        defaultIn(node);
    }

    public void outAAtribEstrelaAAtribEstrela(AAtribEstrelaAAtribEstrela node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtribEstrelaAAtribEstrela(AAtribEstrelaAAtribEstrela node)
    {
        inAAtribEstrelaAAtribEstrela(node);
        if(node.getAAtrib() != null)
        {
            node.getAAtrib().apply(this);
        }
        outAAtribEstrelaAAtribEstrela(node);
    }

    public void inASeAComandoCasado(ASeAComandoCasado node)
    {
        defaultIn(node);
    }

    public void outASeAComandoCasado(ASeAComandoCasado node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASeAComandoCasado(ASeAComandoCasado node)
    {
        inASeAComandoCasado(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        if(node.getAExp() != null)
        {
            node.getAExp().apply(this);
        }
        outASeAComandoCasado(node);
    }

    public void inAOutraAComandoCasado(AOutraAComandoCasado node)
    {
        defaultIn(node);
    }

    public void outAOutraAComandoCasado(AOutraAComandoCasado node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOutraAComandoCasado(AOutraAComandoCasado node)
    {
        inAOutraAComandoCasado(node);
        if(node.getAOutra() != null)
        {
            node.getAOutra().apply(this);
        }
        outAOutraAComandoCasado(node);
    }

    public void inASeAComandoNaoCasado(ASeAComandoNaoCasado node)
    {
        defaultIn(node);
    }

    public void outASeAComandoNaoCasado(ASeAComandoNaoCasado node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASeAComandoNaoCasado(ASeAComandoNaoCasado node)
    {
        inASeAComandoNaoCasado(node);
        if(node.getAComando() != null)
        {
            node.getAComando().apply(this);
        }
        if(node.getAExp() != null)
        {
            node.getAExp().apply(this);
        }
        outASeAComandoNaoCasado(node);
    }

    public void inASeSenaoAComandoNaoCasado(ASeSenaoAComandoNaoCasado node)
    {
        defaultIn(node);
    }

    public void outASeSenaoAComandoNaoCasado(ASeSenaoAComandoNaoCasado node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASeSenaoAComandoNaoCasado(ASeSenaoAComandoNaoCasado node)
    {
        inASeSenaoAComandoNaoCasado(node);
        if(node.getAComandoNaoCasado() != null)
        {
            node.getAComandoNaoCasado().apply(this);
        }
        if(node.getAComandoCasado() != null)
        {
            node.getAComandoCasado().apply(this);
        }
        if(node.getAExp() != null)
        {
            node.getAExp().apply(this);
        }
        outASeSenaoAComandoNaoCasado(node);
    }

    public void inAComandoCasadoAComando(AComandoCasadoAComando node)
    {
        defaultIn(node);
    }

    public void outAComandoCasadoAComando(AComandoCasadoAComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComandoCasadoAComando(AComandoCasadoAComando node)
    {
        inAComandoCasadoAComando(node);
        if(node.getAComandoCasado() != null)
        {
            node.getAComandoCasado().apply(this);
        }
        outAComandoCasadoAComando(node);
    }

    public void inAComandoNaoCasadoAComando(AComandoNaoCasadoAComando node)
    {
        defaultIn(node);
    }

    public void outAComandoNaoCasadoAComando(AComandoNaoCasadoAComando node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAComandoNaoCasadoAComando(AComandoNaoCasadoAComando node)
    {
        inAComandoNaoCasadoAComando(node);
        if(node.getAComandoNaoCasado() != null)
        {
            node.getAComandoNaoCasado().apply(this);
        }
        outAComandoNaoCasadoAComando(node);
    }

    public void inAEnquantoAOutra(AEnquantoAOutra node)
    {
        defaultIn(node);
    }

    public void outAEnquantoAOutra(AEnquantoAOutra node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEnquantoAOutra(AEnquantoAOutra node)
    {
        inAEnquantoAOutra(node);
        if(node.getAComandoCasado() != null)
        {
            node.getAComandoCasado().apply(this);
        }
        if(node.getAExp() != null)
        {
            node.getAExp().apply(this);
        }
        outAEnquantoAOutra(node);
    }

    public void inAParaAOutra(AParaAOutra node)
    {
        defaultIn(node);
    }

    public void outAParaAOutra(AParaAOutra node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParaAOutra(AParaAOutra node)
    {
        inAParaAOutra(node);
        if(node.getAComandoCasado() != null)
        {
            node.getAComandoCasado().apply(this);
        }
        if(node.getAtribDir() != null)
        {
            node.getAtribDir().apply(this);
        }
        if(node.getAExp() != null)
        {
            node.getAExp().apply(this);
        }
        if(node.getAtribEsq() != null)
        {
            node.getAtribEsq().apply(this);
        }
        outAParaAOutra(node);
    }

    public void inAParaCadaAOutra(AParaCadaAOutra node)
    {
        defaultIn(node);
    }

    public void outAParaCadaAOutra(AParaCadaAOutra node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParaCadaAOutra(AParaCadaAOutra node)
    {
        inAParaCadaAOutra(node);
        if(node.getAComandoCasado() != null)
        {
            node.getAComandoCasado().apply(this);
        }
        if(node.getATipo() != null)
        {
            node.getATipo().apply(this);
        }
        outAParaCadaAOutra(node);
    }

    public void inAAtribPontoAOutra(AAtribPontoAOutra node)
    {
        defaultIn(node);
    }

    public void outAAtribPontoAOutra(AAtribPontoAOutra node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAAtribPontoAOutra(AAtribPontoAOutra node)
    {
        inAAtribPontoAOutra(node);
        if(node.getAAtrib() != null)
        {
            node.getAAtrib().apply(this);
        }
        outAAtribPontoAOutra(node);
    }

    public void inARetorneAOutra(ARetorneAOutra node)
    {
        defaultIn(node);
    }

    public void outARetorneAOutra(ARetorneAOutra node)
    {
        defaultOut(node);
    }

    @Override
    public void caseARetorneAOutra(ARetorneAOutra node)
    {
        inARetorneAOutra(node);
        if(node.getAExp() != null)
        {
            node.getAExp().apply(this);
        }
        outARetorneAOutra(node);
    }

    public void inABlocoAOutra(ABlocoAOutra node)
    {
        defaultIn(node);
    }

    public void outABlocoAOutra(ABlocoAOutra node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABlocoAOutra(ABlocoAOutra node)
    {
        inABlocoAOutra(node);
        if(node.getABloco() != null)
        {
            node.getABloco().apply(this);
        }
        outABlocoAOutra(node);
    }

    public void inAChamadaAOutra(AChamadaAOutra node)
    {
        defaultIn(node);
    }

    public void outAChamadaAOutra(AChamadaAOutra node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAChamadaAOutra(AChamadaAOutra node)
    {
        inAChamadaAOutra(node);
        if(node.getAChamada() != null)
        {
            node.getAChamada().apply(this);
        }
        outAChamadaAOutra(node);
    }

    public void inAIdentificadorAVar(AIdentificadorAVar node)
    {
        defaultIn(node);
    }

    public void outAIdentificadorAVar(AIdentificadorAVar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIdentificadorAVar(AIdentificadorAVar node)
    {
        inAIdentificadorAVar(node);
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        outAIdentificadorAVar(node);
    }

    public void inAVarAVar(AVarAVar node)
    {
        defaultIn(node);
    }

    public void outAVarAVar(AVarAVar node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarAVar(AVarAVar node)
    {
        inAVarAVar(node);
        if(node.getAExp() != null)
        {
            node.getAExp().apply(this);
        }
        if(node.getAVar() != null)
        {
            node.getAVar().apply(this);
        }
        outAVarAVar(node);
    }

    public void inASomaAExp(ASomaAExp node)
    {
        defaultIn(node);
    }

    public void outASomaAExp(ASomaAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseASomaAExp(ASomaAExp node)
    {
        inASomaAExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outASomaAExp(node);
    }

    public void inAMenosAExp(AMenosAExp node)
    {
        defaultIn(node);
    }

    public void outAMenosAExp(AMenosAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenosAExp(AMenosAExp node)
    {
        inAMenosAExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAMenosAExp(node);
    }

    public void inAMultAExp(AMultAExp node)
    {
        defaultIn(node);
    }

    public void outAMultAExp(AMultAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMultAExp(AMultAExp node)
    {
        inAMultAExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAMultAExp(node);
    }

    public void inADivAExp(ADivAExp node)
    {
        defaultIn(node);
    }

    public void outADivAExp(ADivAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseADivAExp(ADivAExp node)
    {
        inADivAExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outADivAExp(node);
    }

    public void inAIgualAExp(AIgualAExp node)
    {
        defaultIn(node);
    }

    public void outAIgualAExp(AIgualAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAIgualAExp(AIgualAExp node)
    {
        inAIgualAExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAIgualAExp(node);
    }

    public void inAMenorAExp(AMenorAExp node)
    {
        defaultIn(node);
    }

    public void outAMenorAExp(AMenorAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenorAExp(AMenorAExp node)
    {
        inAMenorAExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAMenorAExp(node);
    }

    public void inAMaiorAExp(AMaiorAExp node)
    {
        defaultIn(node);
    }

    public void outAMaiorAExp(AMaiorAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaiorAExp(AMaiorAExp node)
    {
        inAMaiorAExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAMaiorAExp(node);
    }

    public void inAMenorIgualAExp(AMenorIgualAExp node)
    {
        defaultIn(node);
    }

    public void outAMenorIgualAExp(AMenorIgualAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMenorIgualAExp(AMenorIgualAExp node)
    {
        inAMenorIgualAExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAMenorIgualAExp(node);
    }

    public void inAMaiorIgualAExp(AMaiorIgualAExp node)
    {
        defaultIn(node);
    }

    public void outAMaiorIgualAExp(AMaiorIgualAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAMaiorIgualAExp(AMaiorIgualAExp node)
    {
        inAMaiorIgualAExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAMaiorIgualAExp(node);
    }

    public void inAEAExp(AEAExp node)
    {
        defaultIn(node);
    }

    public void outAEAExp(AEAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAEAExp(AEAExp node)
    {
        inAEAExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAEAExp(node);
    }

    public void inAOuAExp(AOuAExp node)
    {
        defaultIn(node);
    }

    public void outAOuAExp(AOuAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOuAExp(AOuAExp node)
    {
        inAOuAExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        if(node.getEsq() != null)
        {
            node.getEsq().apply(this);
        }
        outAOuAExp(node);
    }

    public void inANaoAExp(ANaoAExp node)
    {
        defaultIn(node);
    }

    public void outANaoAExp(ANaoAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANaoAExp(ANaoAExp node)
    {
        inANaoAExp(node);
        if(node.getDir() != null)
        {
            node.getDir().apply(this);
        }
        outANaoAExp(node);
    }

    public void inAChamadaAExp(AChamadaAExp node)
    {
        defaultIn(node);
    }

    public void outAChamadaAExp(AChamadaAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAChamadaAExp(AChamadaAExp node)
    {
        inAChamadaAExp(node);
        if(node.getAChamada() != null)
        {
            node.getAChamada().apply(this);
        }
        outAChamadaAExp(node);
    }

    public void inAParAExp(AParAExp node)
    {
        defaultIn(node);
    }

    public void outAParAExp(AParAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAParAExp(AParAExp node)
    {
        inAParAExp(node);
        if(node.getAExp() != null)
        {
            node.getAExp().apply(this);
        }
        outAParAExp(node);
    }

    public void inAVarAExp(AVarAExp node)
    {
        defaultIn(node);
    }

    public void outAVarAExp(AVarAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAVarAExp(AVarAExp node)
    {
        inAVarAExp(node);
        if(node.getAVar() != null)
        {
            node.getAVar().apply(this);
        }
        outAVarAExp(node);
    }

    public void inANumeroAExp(ANumeroAExp node)
    {
        defaultIn(node);
    }

    public void outANumeroAExp(ANumeroAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANumeroAExp(ANumeroAExp node)
    {
        inANumeroAExp(node);
        if(node.getNumero() != null)
        {
            node.getNumero().apply(this);
        }
        outANumeroAExp(node);
    }

    public void inACaractereAExp(ACaractereAExp node)
    {
        defaultIn(node);
    }

    public void outACaractereAExp(ACaractereAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseACaractereAExp(ACaractereAExp node)
    {
        inACaractereAExp(node);
        if(node.getCaractere() != null)
        {
            node.getCaractere().apply(this);
        }
        outACaractereAExp(node);
    }

    public void inABooleanoAExp(ABooleanoAExp node)
    {
        defaultIn(node);
    }

    public void outABooleanoAExp(ABooleanoAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseABooleanoAExp(ABooleanoAExp node)
    {
        inABooleanoAExp(node);
        if(node.getBooleano() != null)
        {
            node.getBooleano().apply(this);
        }
        outABooleanoAExp(node);
    }

    public void inAStringAExp(AStringAExp node)
    {
        defaultIn(node);
    }

    public void outAStringAExp(AStringAExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAStringAExp(AStringAExp node)
    {
        inAStringAExp(node);
        if(node.getString() != null)
        {
            node.getString().apply(this);
        }
        outAStringAExp(node);
    }

    public void inAChamadaAChamada(AChamadaAChamada node)
    {
        defaultIn(node);
    }

    public void outAChamadaAChamada(AChamadaAChamada node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAChamadaAChamada(AChamadaAChamada node)
    {
        inAChamadaAChamada(node);
        if(node.getAListaExp() != null)
        {
            node.getAListaExp().apply(this);
        }
        if(node.getIdentificador() != null)
        {
            node.getIdentificador().apply(this);
        }
        outAChamadaAChamada(node);
    }

    public void inANadaAListaExp(ANadaAListaExp node)
    {
        defaultIn(node);
    }

    public void outANadaAListaExp(ANadaAListaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseANadaAListaExp(ANadaAListaExp node)
    {
        inANadaAListaExp(node);
        outANadaAListaExp(node);
    }

    public void inAExpAListaExp(AExpAListaExp node)
    {
        defaultIn(node);
    }

    public void outAExpAListaExp(AExpAListaExp node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAExpAListaExp(AExpAListaExp node)
    {
        inAExpAListaExp(node);
        {
            List<PAOuExpEstrela> copy = new ArrayList<PAOuExpEstrela>(node.getAOuExpEstrela());
            Collections.reverse(copy);
            for(PAOuExpEstrela e : copy)
            {
                e.apply(this);
            }
        }
        if(node.getAExp() != null)
        {
            node.getAExp().apply(this);
        }
        outAExpAListaExp(node);
    }

    public void inAOuExpEstrelaAOuExpEstrela(AOuExpEstrelaAOuExpEstrela node)
    {
        defaultIn(node);
    }

    public void outAOuExpEstrelaAOuExpEstrela(AOuExpEstrelaAOuExpEstrela node)
    {
        defaultOut(node);
    }

    @Override
    public void caseAOuExpEstrelaAOuExpEstrela(AOuExpEstrelaAOuExpEstrela node)
    {
        inAOuExpEstrelaAOuExpEstrela(node);
        if(node.getAExp() != null)
        {
            node.getAExp().apply(this);
        }
        outAOuExpEstrelaAOuExpEstrela(node);
    }
}
