/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AAtribEstrelaAAtribEstrela extends PAAtribEstrela
{
    private PAAtrib _aAtrib_;

    public AAtribEstrelaAAtribEstrela()
    {
        // Constructor
    }

    public AAtribEstrelaAAtribEstrela(
        @SuppressWarnings("hiding") PAAtrib _aAtrib_)
    {
        // Constructor
        setAAtrib(_aAtrib_);

    }

    @Override
    public Object clone()
    {
        return new AAtribEstrelaAAtribEstrela(
            cloneNode(this._aAtrib_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAtribEstrelaAAtribEstrela(this);
    }

    public PAAtrib getAAtrib()
    {
        return this._aAtrib_;
    }

    public void setAAtrib(PAAtrib node)
    {
        if(this._aAtrib_ != null)
        {
            this._aAtrib_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aAtrib_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aAtrib_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aAtrib_ == child)
        {
            this._aAtrib_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aAtrib_ == oldChild)
        {
            setAAtrib((PAAtrib) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
