/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ACaracterePalavraATipoBase extends PATipoBase
{
    private TCaracterePalavra _caracterePalavra_;

    public ACaracterePalavraATipoBase()
    {
        // Constructor
    }

    public ACaracterePalavraATipoBase(
        @SuppressWarnings("hiding") TCaracterePalavra _caracterePalavra_)
    {
        // Constructor
        setCaracterePalavra(_caracterePalavra_);

    }

    @Override
    public Object clone()
    {
        return new ACaracterePalavraATipoBase(
            cloneNode(this._caracterePalavra_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACaracterePalavraATipoBase(this);
    }

    public TCaracterePalavra getCaracterePalavra()
    {
        return this._caracterePalavra_;
    }

    public void setCaracterePalavra(TCaracterePalavra node)
    {
        if(this._caracterePalavra_ != null)
        {
            this._caracterePalavra_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._caracterePalavra_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._caracterePalavra_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._caracterePalavra_ == child)
        {
            this._caracterePalavra_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._caracterePalavra_ == oldChild)
        {
            setCaracterePalavra((TCaracterePalavra) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
