/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AChamadaAOutra extends PAOutra
{
    private PAChamada _aChamada_;

    public AChamadaAOutra()
    {
        // Constructor
    }

    public AChamadaAOutra(
        @SuppressWarnings("hiding") PAChamada _aChamada_)
    {
        // Constructor
        setAChamada(_aChamada_);

    }

    @Override
    public Object clone()
    {
        return new AChamadaAOutra(
            cloneNode(this._aChamada_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAChamadaAOutra(this);
    }

    public PAChamada getAChamada()
    {
        return this._aChamada_;
    }

    public void setAChamada(PAChamada node)
    {
        if(this._aChamada_ != null)
        {
            this._aChamada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aChamada_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aChamada_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aChamada_ == child)
        {
            this._aChamada_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aChamada_ == oldChild)
        {
            setAChamada((PAChamada) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
