/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AChamadaAChamada extends PAChamada
{
    private TIdentificador _identificador_;
    private PAListaExp _aListaExp_;

    public AChamadaAChamada()
    {
        // Constructor
    }

    public AChamadaAChamada(
        @SuppressWarnings("hiding") TIdentificador _identificador_,
        @SuppressWarnings("hiding") PAListaExp _aListaExp_)
    {
        // Constructor
        setIdentificador(_identificador_);

        setAListaExp(_aListaExp_);

    }

    @Override
    public Object clone()
    {
        return new AChamadaAChamada(
            cloneNode(this._identificador_),
            cloneNode(this._aListaExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAChamadaAChamada(this);
    }

    public TIdentificador getIdentificador()
    {
        return this._identificador_;
    }

    public void setIdentificador(TIdentificador node)
    {
        if(this._identificador_ != null)
        {
            this._identificador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identificador_ = node;
    }

    public PAListaExp getAListaExp()
    {
        return this._aListaExp_;
    }

    public void setAListaExp(PAListaExp node)
    {
        if(this._aListaExp_ != null)
        {
            this._aListaExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aListaExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identificador_)
            + toString(this._aListaExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identificador_ == child)
        {
            this._identificador_ = null;
            return;
        }

        if(this._aListaExp_ == child)
        {
            this._aListaExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identificador_ == oldChild)
        {
            setIdentificador((TIdentificador) newChild);
            return;
        }

        if(this._aListaExp_ == oldChild)
        {
            setAListaExp((PAListaExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
