/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AComandoCasadoAComando extends PAComando
{
    private PAComandoCasado _aComandoCasado_;

    public AComandoCasadoAComando()
    {
        // Constructor
    }

    public AComandoCasadoAComando(
        @SuppressWarnings("hiding") PAComandoCasado _aComandoCasado_)
    {
        // Constructor
        setAComandoCasado(_aComandoCasado_);

    }

    @Override
    public Object clone()
    {
        return new AComandoCasadoAComando(
            cloneNode(this._aComandoCasado_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComandoCasadoAComando(this);
    }

    public PAComandoCasado getAComandoCasado()
    {
        return this._aComandoCasado_;
    }

    public void setAComandoCasado(PAComandoCasado node)
    {
        if(this._aComandoCasado_ != null)
        {
            this._aComandoCasado_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aComandoCasado_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aComandoCasado_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aComandoCasado_ == child)
        {
            this._aComandoCasado_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aComandoCasado_ == oldChild)
        {
            setAComandoCasado((PAComandoCasado) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
