/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AComandoNaoCasadoAComando extends PAComando
{
    private PAComandoNaoCasado _aComandoNaoCasado_;

    public AComandoNaoCasadoAComando()
    {
        // Constructor
    }

    public AComandoNaoCasadoAComando(
        @SuppressWarnings("hiding") PAComandoNaoCasado _aComandoNaoCasado_)
    {
        // Constructor
        setAComandoNaoCasado(_aComandoNaoCasado_);

    }

    @Override
    public Object clone()
    {
        return new AComandoNaoCasadoAComando(
            cloneNode(this._aComandoNaoCasado_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAComandoNaoCasadoAComando(this);
    }

    public PAComandoNaoCasado getAComandoNaoCasado()
    {
        return this._aComandoNaoCasado_;
    }

    public void setAComandoNaoCasado(PAComandoNaoCasado node)
    {
        if(this._aComandoNaoCasado_ != null)
        {
            this._aComandoNaoCasado_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aComandoNaoCasado_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aComandoNaoCasado_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aComandoNaoCasado_ == child)
        {
            this._aComandoNaoCasado_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aComandoNaoCasado_ == oldChild)
        {
            setAComandoNaoCasado((PAComandoNaoCasado) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
