/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import java.util.*;
import caju.analysis.*;

@SuppressWarnings("nls")
public final class AExpAListaExp extends PAListaExp
{
    private PAExp _aExp_;
    private final LinkedList<PAOuExpEstrela> _aOuExpEstrela_ = new LinkedList<PAOuExpEstrela>();

    public AExpAListaExp()
    {
        // Constructor
    }

    public AExpAListaExp(
        @SuppressWarnings("hiding") PAExp _aExp_,
        @SuppressWarnings("hiding") List<?> _aOuExpEstrela_)
    {
        // Constructor
        setAExp(_aExp_);

        setAOuExpEstrela(_aOuExpEstrela_);

    }

    @Override
    public Object clone()
    {
        return new AExpAListaExp(
            cloneNode(this._aExp_),
            cloneList(this._aOuExpEstrela_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpAListaExp(this);
    }

    public PAExp getAExp()
    {
        return this._aExp_;
    }

    public void setAExp(PAExp node)
    {
        if(this._aExp_ != null)
        {
            this._aExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aExp_ = node;
    }

    public LinkedList<PAOuExpEstrela> getAOuExpEstrela()
    {
        return this._aOuExpEstrela_;
    }

    public void setAOuExpEstrela(List<?> list)
    {
        for(PAOuExpEstrela e : this._aOuExpEstrela_)
        {
            e.parent(null);
        }
        this._aOuExpEstrela_.clear();

        for(Object obj_e : list)
        {
            PAOuExpEstrela e = (PAOuExpEstrela) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._aOuExpEstrela_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aExp_)
            + toString(this._aOuExpEstrela_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aExp_ == child)
        {
            this._aExp_ = null;
            return;
        }

        if(this._aOuExpEstrela_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aExp_ == oldChild)
        {
            setAExp((PAExp) newChild);
            return;
        }

        for(ListIterator<PAOuExpEstrela> i = this._aOuExpEstrela_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAOuExpEstrela) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
