/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AIdentificadoresAListaNomes extends PAListaNomes
{
    private TIdentificador _identificador_;
    private PAListaNomes _aListaNomes_;

    public AIdentificadoresAListaNomes()
    {
        // Constructor
    }

    public AIdentificadoresAListaNomes(
        @SuppressWarnings("hiding") TIdentificador _identificador_,
        @SuppressWarnings("hiding") PAListaNomes _aListaNomes_)
    {
        // Constructor
        setIdentificador(_identificador_);

        setAListaNomes(_aListaNomes_);

    }

    @Override
    public Object clone()
    {
        return new AIdentificadoresAListaNomes(
            cloneNode(this._identificador_),
            cloneNode(this._aListaNomes_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIdentificadoresAListaNomes(this);
    }

    public TIdentificador getIdentificador()
    {
        return this._identificador_;
    }

    public void setIdentificador(TIdentificador node)
    {
        if(this._identificador_ != null)
        {
            this._identificador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identificador_ = node;
    }

    public PAListaNomes getAListaNomes()
    {
        return this._aListaNomes_;
    }

    public void setAListaNomes(PAListaNomes node)
    {
        if(this._aListaNomes_ != null)
        {
            this._aListaNomes_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aListaNomes_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identificador_)
            + toString(this._aListaNomes_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identificador_ == child)
        {
            this._identificador_ = null;
            return;
        }

        if(this._aListaNomes_ == child)
        {
            this._aListaNomes_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identificador_ == oldChild)
        {
            setIdentificador((TIdentificador) newChild);
            return;
        }

        if(this._aListaNomes_ == oldChild)
        {
            setAListaNomes((PAListaNomes) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
