/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import java.util.*;
import caju.analysis.*;

@SuppressWarnings("nls")
public final class AListaAtribAListaAtrib extends PAListaAtrib
{
    private PAAtrib _aAtrib_;
    private final LinkedList<PAAtribEstrela> _aAtribEstrela_ = new LinkedList<PAAtribEstrela>();

    public AListaAtribAListaAtrib()
    {
        // Constructor
    }

    public AListaAtribAListaAtrib(
        @SuppressWarnings("hiding") PAAtrib _aAtrib_,
        @SuppressWarnings("hiding") List<?> _aAtribEstrela_)
    {
        // Constructor
        setAAtrib(_aAtrib_);

        setAAtribEstrela(_aAtribEstrela_);

    }

    @Override
    public Object clone()
    {
        return new AListaAtribAListaAtrib(
            cloneNode(this._aAtrib_),
            cloneList(this._aAtribEstrela_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaAtribAListaAtrib(this);
    }

    public PAAtrib getAAtrib()
    {
        return this._aAtrib_;
    }

    public void setAAtrib(PAAtrib node)
    {
        if(this._aAtrib_ != null)
        {
            this._aAtrib_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aAtrib_ = node;
    }

    public LinkedList<PAAtribEstrela> getAAtribEstrela()
    {
        return this._aAtribEstrela_;
    }

    public void setAAtribEstrela(List<?> list)
    {
        for(PAAtribEstrela e : this._aAtribEstrela_)
        {
            e.parent(null);
        }
        this._aAtribEstrela_.clear();

        for(Object obj_e : list)
        {
            PAAtribEstrela e = (PAAtribEstrela) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._aAtribEstrela_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aAtrib_)
            + toString(this._aAtribEstrela_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aAtrib_ == child)
        {
            this._aAtrib_ = null;
            return;
        }

        if(this._aAtribEstrela_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aAtrib_ == oldChild)
        {
            setAAtrib((PAAtrib) newChild);
            return;
        }

        for(ListIterator<PAAtribEstrela> i = this._aAtribEstrela_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAAtribEstrela) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
