/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ANaoAExp extends PAExp
{
    private PAExp _dir_;

    public ANaoAExp()
    {
        // Constructor
    }

    public ANaoAExp(
        @SuppressWarnings("hiding") PAExp _dir_)
    {
        // Constructor
        setDir(_dir_);

    }

    @Override
    public Object clone()
    {
        return new ANaoAExp(
            cloneNode(this._dir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANaoAExp(this);
    }

    public PAExp getDir()
    {
        return this._dir_;
    }

    public void setDir(PAExp node)
    {
        if(this._dir_ != null)
        {
            this._dir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._dir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._dir_ == child)
        {
            this._dir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._dir_ == oldChild)
        {
            setDir((PAExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
