/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AOutraAComandoCasado extends PAComandoCasado
{
    private PAOutra _aOutra_;

    public AOutraAComandoCasado()
    {
        // Constructor
    }

    public AOutraAComandoCasado(
        @SuppressWarnings("hiding") PAOutra _aOutra_)
    {
        // Constructor
        setAOutra(_aOutra_);

    }

    @Override
    public Object clone()
    {
        return new AOutraAComandoCasado(
            cloneNode(this._aOutra_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOutraAComandoCasado(this);
    }

    public PAOutra getAOutra()
    {
        return this._aOutra_;
    }

    public void setAOutra(PAOutra node)
    {
        if(this._aOutra_ != null)
        {
            this._aOutra_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aOutra_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aOutra_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aOutra_ == child)
        {
            this._aOutra_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aOutra_ == oldChild)
        {
            setAOutra((PAOutra) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
