/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import java.util.*;
import caju.analysis.*;

@SuppressWarnings("nls")
public final class AParametrosAParametros extends PAParametros
{
    private PAParametro _aParametro_;
    private final LinkedList<PAParametroEstrela> _aParametroEstrela_ = new LinkedList<PAParametroEstrela>();

    public AParametrosAParametros()
    {
        // Constructor
    }

    public AParametrosAParametros(
        @SuppressWarnings("hiding") PAParametro _aParametro_,
        @SuppressWarnings("hiding") List<?> _aParametroEstrela_)
    {
        // Constructor
        setAParametro(_aParametro_);

        setAParametroEstrela(_aParametroEstrela_);

    }

    @Override
    public Object clone()
    {
        return new AParametrosAParametros(
            cloneNode(this._aParametro_),
            cloneList(this._aParametroEstrela_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParametrosAParametros(this);
    }

    public PAParametro getAParametro()
    {
        return this._aParametro_;
    }

    public void setAParametro(PAParametro node)
    {
        if(this._aParametro_ != null)
        {
            this._aParametro_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aParametro_ = node;
    }

    public LinkedList<PAParametroEstrela> getAParametroEstrela()
    {
        return this._aParametroEstrela_;
    }

    public void setAParametroEstrela(List<?> list)
    {
        for(PAParametroEstrela e : this._aParametroEstrela_)
        {
            e.parent(null);
        }
        this._aParametroEstrela_.clear();

        for(Object obj_e : list)
        {
            PAParametroEstrela e = (PAParametroEstrela) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._aParametroEstrela_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aParametro_)
            + toString(this._aParametroEstrela_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aParametro_ == child)
        {
            this._aParametro_ = null;
            return;
        }

        if(this._aParametroEstrela_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aParametro_ == oldChild)
        {
            setAParametro((PAParametro) newChild);
            return;
        }

        for(ListIterator<PAParametroEstrela> i = this._aParametroEstrela_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAParametroEstrela) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
