/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AParaCadaAOutra extends PAOutra
{
    private PATipo _aTipo_;
    private PAComandoCasado _aComandoCasado_;

    public AParaCadaAOutra()
    {
        // Constructor
    }

    public AParaCadaAOutra(
        @SuppressWarnings("hiding") PATipo _aTipo_,
        @SuppressWarnings("hiding") PAComandoCasado _aComandoCasado_)
    {
        // Constructor
        setATipo(_aTipo_);

        setAComandoCasado(_aComandoCasado_);

    }

    @Override
    public Object clone()
    {
        return new AParaCadaAOutra(
            cloneNode(this._aTipo_),
            cloneNode(this._aComandoCasado_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParaCadaAOutra(this);
    }

    public PATipo getATipo()
    {
        return this._aTipo_;
    }

    public void setATipo(PATipo node)
    {
        if(this._aTipo_ != null)
        {
            this._aTipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aTipo_ = node;
    }

    public PAComandoCasado getAComandoCasado()
    {
        return this._aComandoCasado_;
    }

    public void setAComandoCasado(PAComandoCasado node)
    {
        if(this._aComandoCasado_ != null)
        {
            this._aComandoCasado_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aComandoCasado_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aTipo_)
            + toString(this._aComandoCasado_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aTipo_ == child)
        {
            this._aTipo_ = null;
            return;
        }

        if(this._aComandoCasado_ == child)
        {
            this._aComandoCasado_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aTipo_ == oldChild)
        {
            setATipo((PATipo) newChild);
            return;
        }

        if(this._aComandoCasado_ == oldChild)
        {
            setAComandoCasado((PAComandoCasado) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
