/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AParaAOutra extends PAOutra
{
    private PAListaAtrib _atribEsq_;
    private PAExp _aExp_;
    private PAListaAtrib _atribDir_;
    private PAComandoCasado _aComandoCasado_;

    public AParaAOutra()
    {
        // Constructor
    }

    public AParaAOutra(
        @SuppressWarnings("hiding") PAListaAtrib _atribEsq_,
        @SuppressWarnings("hiding") PAExp _aExp_,
        @SuppressWarnings("hiding") PAListaAtrib _atribDir_,
        @SuppressWarnings("hiding") PAComandoCasado _aComandoCasado_)
    {
        // Constructor
        setAtribEsq(_atribEsq_);

        setAExp(_aExp_);

        setAtribDir(_atribDir_);

        setAComandoCasado(_aComandoCasado_);

    }

    @Override
    public Object clone()
    {
        return new AParaAOutra(
            cloneNode(this._atribEsq_),
            cloneNode(this._aExp_),
            cloneNode(this._atribDir_),
            cloneNode(this._aComandoCasado_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParaAOutra(this);
    }

    public PAListaAtrib getAtribEsq()
    {
        return this._atribEsq_;
    }

    public void setAtribEsq(PAListaAtrib node)
    {
        if(this._atribEsq_ != null)
        {
            this._atribEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atribEsq_ = node;
    }

    public PAExp getAExp()
    {
        return this._aExp_;
    }

    public void setAExp(PAExp node)
    {
        if(this._aExp_ != null)
        {
            this._aExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aExp_ = node;
    }

    public PAListaAtrib getAtribDir()
    {
        return this._atribDir_;
    }

    public void setAtribDir(PAListaAtrib node)
    {
        if(this._atribDir_ != null)
        {
            this._atribDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atribDir_ = node;
    }

    public PAComandoCasado getAComandoCasado()
    {
        return this._aComandoCasado_;
    }

    public void setAComandoCasado(PAComandoCasado node)
    {
        if(this._aComandoCasado_ != null)
        {
            this._aComandoCasado_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aComandoCasado_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._atribEsq_)
            + toString(this._aExp_)
            + toString(this._atribDir_)
            + toString(this._aComandoCasado_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._atribEsq_ == child)
        {
            this._atribEsq_ = null;
            return;
        }

        if(this._aExp_ == child)
        {
            this._aExp_ = null;
            return;
        }

        if(this._atribDir_ == child)
        {
            this._atribDir_ = null;
            return;
        }

        if(this._aComandoCasado_ == child)
        {
            this._aComandoCasado_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._atribEsq_ == oldChild)
        {
            setAtribEsq((PAListaAtrib) newChild);
            return;
        }

        if(this._aExp_ == oldChild)
        {
            setAExp((PAExp) newChild);
            return;
        }

        if(this._atribDir_ == oldChild)
        {
            setAtribDir((PAListaAtrib) newChild);
            return;
        }

        if(this._aComandoCasado_ == oldChild)
        {
            setAComandoCasado((PAComandoCasado) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
