/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ASeAComandoCasado extends PAComandoCasado
{
    private PAExp _aExp_;
    private PAComandoCasado _esq_;
    private PAComandoCasado _dir_;

    public ASeAComandoCasado()
    {
        // Constructor
    }

    public ASeAComandoCasado(
        @SuppressWarnings("hiding") PAExp _aExp_,
        @SuppressWarnings("hiding") PAComandoCasado _esq_,
        @SuppressWarnings("hiding") PAComandoCasado _dir_)
    {
        // Constructor
        setAExp(_aExp_);

        setEsq(_esq_);

        setDir(_dir_);

    }

    @Override
    public Object clone()
    {
        return new ASeAComandoCasado(
            cloneNode(this._aExp_),
            cloneNode(this._esq_),
            cloneNode(this._dir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASeAComandoCasado(this);
    }

    public PAExp getAExp()
    {
        return this._aExp_;
    }

    public void setAExp(PAExp node)
    {
        if(this._aExp_ != null)
        {
            this._aExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aExp_ = node;
    }

    public PAComandoCasado getEsq()
    {
        return this._esq_;
    }

    public void setEsq(PAComandoCasado node)
    {
        if(this._esq_ != null)
        {
            this._esq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._esq_ = node;
    }

    public PAComandoCasado getDir()
    {
        return this._dir_;
    }

    public void setDir(PAComandoCasado node)
    {
        if(this._dir_ != null)
        {
            this._dir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aExp_)
            + toString(this._esq_)
            + toString(this._dir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aExp_ == child)
        {
            this._aExp_ = null;
            return;
        }

        if(this._esq_ == child)
        {
            this._esq_ = null;
            return;
        }

        if(this._dir_ == child)
        {
            this._dir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aExp_ == oldChild)
        {
            setAExp((PAExp) newChild);
            return;
        }

        if(this._esq_ == oldChild)
        {
            setEsq((PAComandoCasado) newChild);
            return;
        }

        if(this._dir_ == oldChild)
        {
            setDir((PAComandoCasado) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
