/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ASeSenaoAComandoNaoCasado extends PAComandoNaoCasado
{
    private PAExp _aExp_;
    private PAComandoCasado _aComandoCasado_;
    private PAComandoNaoCasado _aComandoNaoCasado_;

    public ASeSenaoAComandoNaoCasado()
    {
        // Constructor
    }

    public ASeSenaoAComandoNaoCasado(
        @SuppressWarnings("hiding") PAExp _aExp_,
        @SuppressWarnings("hiding") PAComandoCasado _aComandoCasado_,
        @SuppressWarnings("hiding") PAComandoNaoCasado _aComandoNaoCasado_)
    {
        // Constructor
        setAExp(_aExp_);

        setAComandoCasado(_aComandoCasado_);

        setAComandoNaoCasado(_aComandoNaoCasado_);

    }

    @Override
    public Object clone()
    {
        return new ASeSenaoAComandoNaoCasado(
            cloneNode(this._aExp_),
            cloneNode(this._aComandoCasado_),
            cloneNode(this._aComandoNaoCasado_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASeSenaoAComandoNaoCasado(this);
    }

    public PAExp getAExp()
    {
        return this._aExp_;
    }

    public void setAExp(PAExp node)
    {
        if(this._aExp_ != null)
        {
            this._aExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aExp_ = node;
    }

    public PAComandoCasado getAComandoCasado()
    {
        return this._aComandoCasado_;
    }

    public void setAComandoCasado(PAComandoCasado node)
    {
        if(this._aComandoCasado_ != null)
        {
            this._aComandoCasado_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aComandoCasado_ = node;
    }

    public PAComandoNaoCasado getAComandoNaoCasado()
    {
        return this._aComandoNaoCasado_;
    }

    public void setAComandoNaoCasado(PAComandoNaoCasado node)
    {
        if(this._aComandoNaoCasado_ != null)
        {
            this._aComandoNaoCasado_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aComandoNaoCasado_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aExp_)
            + toString(this._aComandoCasado_)
            + toString(this._aComandoNaoCasado_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aExp_ == child)
        {
            this._aExp_ = null;
            return;
        }

        if(this._aComandoCasado_ == child)
        {
            this._aComandoCasado_ = null;
            return;
        }

        if(this._aComandoNaoCasado_ == child)
        {
            this._aComandoNaoCasado_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aExp_ == oldChild)
        {
            setAExp((PAExp) newChild);
            return;
        }

        if(this._aComandoCasado_ == oldChild)
        {
            setAComandoCasado((PAComandoCasado) newChild);
            return;
        }

        if(this._aComandoNaoCasado_ == oldChild)
        {
            setAComandoNaoCasado((PAComandoNaoCasado) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
