/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ATipoATipoRetorno extends PATipoRetorno
{
    private PATipo _aTipo_;

    public ATipoATipoRetorno()
    {
        // Constructor
    }

    public ATipoATipoRetorno(
        @SuppressWarnings("hiding") PATipo _aTipo_)
    {
        // Constructor
        setATipo(_aTipo_);

    }

    @Override
    public Object clone()
    {
        return new ATipoATipoRetorno(
            cloneNode(this._aTipo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATipoATipoRetorno(this);
    }

    public PATipo getATipo()
    {
        return this._aTipo_;
    }

    public void setATipo(PATipo node)
    {
        if(this._aTipo_ != null)
        {
            this._aTipo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aTipo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aTipo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aTipo_ == child)
        {
            this._aTipo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aTipo_ == oldChild)
        {
            setATipo((PATipo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
