/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import java.util.*;
import caju.analysis.*;

@SuppressWarnings("nls")
public final class AVetorATipo extends PATipo
{
    private PATipoBase _aTipoBase_;
    private PAExp _aExp_;
    private final LinkedList<PAVetorEstrela> _aVetorEstrela_ = new LinkedList<PAVetorEstrela>();

    public AVetorATipo()
    {
        // Constructor
    }

    public AVetorATipo(
        @SuppressWarnings("hiding") PATipoBase _aTipoBase_,
        @SuppressWarnings("hiding") PAExp _aExp_,
        @SuppressWarnings("hiding") List<?> _aVetorEstrela_)
    {
        // Constructor
        setATipoBase(_aTipoBase_);

        setAExp(_aExp_);

        setAVetorEstrela(_aVetorEstrela_);

    }

    @Override
    public Object clone()
    {
        return new AVetorATipo(
            cloneNode(this._aTipoBase_),
            cloneNode(this._aExp_),
            cloneList(this._aVetorEstrela_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVetorATipo(this);
    }

    public PATipoBase getATipoBase()
    {
        return this._aTipoBase_;
    }

    public void setATipoBase(PATipoBase node)
    {
        if(this._aTipoBase_ != null)
        {
            this._aTipoBase_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aTipoBase_ = node;
    }

    public PAExp getAExp()
    {
        return this._aExp_;
    }

    public void setAExp(PAExp node)
    {
        if(this._aExp_ != null)
        {
            this._aExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aExp_ = node;
    }

    public LinkedList<PAVetorEstrela> getAVetorEstrela()
    {
        return this._aVetorEstrela_;
    }

    public void setAVetorEstrela(List<?> list)
    {
        for(PAVetorEstrela e : this._aVetorEstrela_)
        {
            e.parent(null);
        }
        this._aVetorEstrela_.clear();

        for(Object obj_e : list)
        {
            PAVetorEstrela e = (PAVetorEstrela) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._aVetorEstrela_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aTipoBase_)
            + toString(this._aExp_)
            + toString(this._aVetorEstrela_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aTipoBase_ == child)
        {
            this._aTipoBase_ = null;
            return;
        }

        if(this._aExp_ == child)
        {
            this._aExp_ = null;
            return;
        }

        if(this._aVetorEstrela_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aTipoBase_ == oldChild)
        {
            setATipoBase((PATipoBase) newChild);
            return;
        }

        if(this._aExp_ == oldChild)
        {
            setAExp((PAExp) newChild);
            return;
        }

        for(ListIterator<PAVetorEstrela> i = this._aVetorEstrela_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAVetorEstrela) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
