/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class TNumeroPalavra extends Token
{
    public TNumeroPalavra()
    {
        super.setText("numero");
    }

    public TNumeroPalavra(int line, int pos)
    {
        super.setText("numero");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNumeroPalavra(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNumeroPalavra(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNumeroPalavra text.");
    }
}
