/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class TVetorPalavra extends Token
{
    public TVetorPalavra()
    {
        super.setText("vetor");
    }

    public TVetorPalavra(int line, int pos)
    {
        super.setText("vetor");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TVetorPalavra(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTVetorPalavra(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TVetorPalavra text.");
    }
}
