/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.analysis;

import java.util.*;
import caju.node.*;

public class AnalysisAdapter implements Analysis
{
    private Hashtable<Node,Object> in;
    private Hashtable<Node,Object> out;

    @Override
    public Object getIn(Node node)
    {
        if(this.in == null)
        {
            return null;
        }

        return this.in.get(node);
    }

    @Override
    public void setIn(Node node, Object o)
    {
        if(this.in == null)
        {
            this.in = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.in.put(node, o);
        }
        else
        {
            this.in.remove(node);
        }
    }

    @Override
    public Object getOut(Node node)
    {
        if(this.out == null)
        {
            return null;
        }

        return this.out.get(node);
    }

    @Override
    public void setOut(Node node, Object o)
    {
        if(this.out == null)
        {
            this.out = new Hashtable<Node,Object>(1);
        }

        if(o != null)
        {
            this.out.put(node, o);
        }
        else
        {
            this.out.remove(node);
        }
    }

    @Override
    public void caseStart(Start node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPrograma(APrograma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADecVariavel(ADecVariavel node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIdentificadoresListaNomes(AIdentificadoresListaNomes node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIdentificadorListaNomes(AIdentificadorListaNomes node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATipoBaseTipo(ATipoBaseTipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVetorTipo(AVetorTipo node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVetorEstrela(AVetorEstrela node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABooleanoPalavraTipoBase(ABooleanoPalavraTipoBase node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACaracterePalavraTipoBase(ACaracterePalavraTipoBase node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANumeroPalavraTipoBase(ANumeroPalavraTipoBase node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADecFuncao(ADecFuncao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseATipoTipoRetorno(ATipoTipoRetorno node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVazioTipoRetorno(AVazioTipoRetorno node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANadaParametros(ANadaParametros node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVariosParametrosParametros(AVariosParametrosParametros node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParametro(AParametro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParametroEstrela(AParametroEstrela node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABloco(ABloco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAtrib(AAtrib node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAListaAtrib(AListaAtrib node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAtribEstrela(AAtribEstrela node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComandoComando(AComandoComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAComandoSemOpcionalComando(AComandoSemOpcionalComando node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASeComandoCasam(ASeComandoCasam node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOutraComandoCasam(AOutraComandoCasam node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASeComandoSemCasam(ASeComandoSemCasam node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAEnquantoOutra(AEnquantoOutra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParaOutra(AParaOutra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParaCadaOutra(AParaCadaOutra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAAtribPontoOutra(AAtribPontoOutra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseARetorneOutra(ARetorneOutra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABlocoOutra(ABlocoOutra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAChamadaOutra(AChamadaOutra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAIdentificadorVar(AIdentificadorVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVarVar(AVarVar node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAChamadaExp(AChamadaExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANivelZeroExp(ANivelZeroExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANivelUmExp(ANivelUmExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPreceOu(APreceOu node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPreceE(APreceE node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANivelUmNivelUm(ANivelUmNivelUm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANivelDoisNivelUm(ANivelDoisNivelUm node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPreceIgual(APreceIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANivelDoisNivelDois(ANivelDoisNivelDois node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANivelTresNivelDois(ANivelTresNivelDois node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMenorIgualPreceMaiorMenorIgual(AMenorIgualPreceMaiorMenorIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMaiorIgualPreceMaiorMenorIgual(AMaiorIgualPreceMaiorMenorIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMenorPreceMaiorMenorIgual(AMenorPreceMaiorMenorIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMaiorPreceMaiorMenorIgual(AMaiorPreceMaiorMenorIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANivelTresNivelTres(ANivelTresNivelTres node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANivelQuatroNivelTres(ANivelQuatroNivelTres node)
    {
        defaultCase(node);
    }

    @Override
    public void caseASomaPreceSomaMenos(ASomaPreceSomaMenos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMenosPreceSomaMenos(AMenosPreceSomaMenos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANivelQuatroNivelQuatro(ANivelQuatroNivelQuatro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANivelCincoNivelQuatro(ANivelCincoNivelQuatro node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAMultPreceMultDiv(AMultPreceMultDiv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseADivPreceMultDiv(ADivPreceMultDiv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANivelCincoNivelCinco(ANivelCincoNivelCinco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANivelSeisNivelCinco(ANivelSeisNivelCinco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPreceNao(APreceNao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANivelSeisNivelSeis(ANivelSeisNivelSeis node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAPreceParValorNivelSeis(APreceParValorNivelSeis node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAParExpPreceParValor(AParExpPreceParValor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAVarPreceParValor(AVarPreceParValor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANumeroPreceParValor(ANumeroPreceParValor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseACaracterePreceParValor(ACaracterePreceParValor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAStringPreceParValor(AStringPreceParValor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseABooleanoPreceParValor(ABooleanoPreceParValor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAChamada(AChamada node)
    {
        defaultCase(node);
    }

    @Override
    public void caseANadaListaExp(ANadaListaExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAExpListaExp(AExpListaExp node)
    {
        defaultCase(node);
    }

    @Override
    public void caseAOuExpEstrela(AOuExpEstrela node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNumero(TNumero node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSoma(TSoma node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMenos(TMenos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMult(TMult node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDiv(TDiv node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIgual(TIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMaior(TMaior node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMenor(TMenor node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMaiorIgual(TMaiorIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTMenorIgual(TMenorIgual node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTInicio(TInicio node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTFim(TFim node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBooleanoPalavra(TBooleanoPalavra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNumeroPalavra(TNumeroPalavra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCaracterePalavra(TCaracterePalavra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVetorPalavra(TVetorPalavra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPalavraVazio(TPalavraVazio node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTString(TString node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParEsq(TParEsq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParDir(TParDir node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTColcheteEsq(TColcheteEsq node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTColcheteDir(TColcheteDir node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPonto(TPonto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVirgula(TVirgula node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBarra(TBarra node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPontoEVirgula(TPontoEVirgula node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIniciador(TIniciador node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTAtribuicao(TAtribuicao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTDoisPontos(TDoisPontos node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTBooleano(TBooleano node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTEnquanto(TEnquanto node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTParaCada(TParaCada node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTPara(TPara node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTRetorne(TRetorne node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSe(TSe node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTSenao(TSenao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTNao(TNao node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTE(TE node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTOu(TOu node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTVazio(TVazio node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTCaractere(TCaractere node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTIdentificador(TIdentificador node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComentarioLinha(TComentarioLinha node)
    {
        defaultCase(node);
    }

    @Override
    public void caseTComentarioBloco(TComentarioBloco node)
    {
        defaultCase(node);
    }

    @Override
    public void caseEOF(EOF node)
    {
        defaultCase(node);
    }

    @Override
    public void caseInvalidToken(InvalidToken node)
    {
        defaultCase(node);
    }

    public void defaultCase(@SuppressWarnings("unused") Node node)
    {
        // do nothing
    }
}
